networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  mysql:
    driver: local
  percona:
    driver: local
  mssql:
    driver: local
  postgres:
    driver: local
  memcached:
    driver: local
  redis:
    driver: local
  neo4j:
    driver: local
  mariadb:
    driver: local
  mongo:
    driver: local
  minio:
    driver: local
  rethinkdb:
    driver: local
  phpmyadmin:
    driver: local
  adminer:
    driver: local
  confluence:
    driver: local
  sonarqube:
    driver: local
  cassandra:
    driver: local
  graylog:
    driver: local
  docker-in-docker:
    driver: local

services:

### Workspace Utilities ##################################
    workspace:
      build:
        context: ./workspace
        args:
          - CHANGE_SOURCE=false
          - SHELL_OH_MY_ZSH=false
          - SHELL_OH_MY_ZSH_AUTOSUGESTIONS=false
          - SHELL_OH_MY_ZSH_ALIASES=false
          - BASE_IMAGE_TAG_PREFIX=latest
          - LARADOCK_PHP_VERSION=8.0
          - LARADOCK_PHALCON_VERSION=4.0.5
          - INSTALL_SUBVERSION=false
          - INSTALL_BZ2=false
          - INSTALL_GMP=false
          - INSTALL_GNUPG=false
          - INSTALL_XDEBUG=false
          - INSTALL_PCOV=false
          - INSTALL_PHPDBG=false
          - INSTALL_BLACKFIRE=false
          - INSTALL_SSH2=false
          - INSTALL_SOAP=false
          - INSTALL_XSL=false
          - INSTALL_LDAP=false
          - INSTALL_SMB=false
          - INSTALL_IMAP=false
          - INSTALL_MONGO=false
          - INSTALL_AMQP=false
          - INSTALL_CASSANDRA=false
          - INSTALL_ZMQ=false
          - INSTALL_GEARMAN=false
          - INSTALL_PHPREDIS=true
          - INSTALL_MSSQL=false
          - NVM_NODEJS_ORG_MIRROR=
          - INSTALL_NODE=true
          - NPM_REGISTRY=
          - NPM_FETCH_RETRIES=2
          - NPM_FETCH_RETRY_FACTOR=10
          - NPM_FETCH_RETRY_MINTIMEOUT=10000
          - NPM_FETCH_RETRY_MAXTIMEOUT=60000
          - INSTALL_PNPM=false
          - INSTALL_YARN=true
          - INSTALL_NPM_GULP=true
          - INSTALL_NPM_BOWER=false
          - INSTALL_NPM_VUE_CLI=true
          - INSTALL_NPM_ANGULAR_CLI=false
          - INSTALL_DRUSH=false
          - INSTALL_WP_CLI=false
          - INSTALL_DRUPAL_CONSOLE=false
          - INSTALL_AEROSPIKE=false
          - INSTALL_OCI8=false
          - INSTALL_V8JS=false
          - COMPOSER_GLOBAL_INSTALL=true
          - COMPOSER_VERSION=2
          - COMPOSER_AUTH_JSON=false
          - COMPOSER_REPO_PACKAGIST=
          - INSTALL_WORKSPACE_SSH=false
          - INSTALL_LARAVEL_ENVOY=false
          - INSTALL_LARAVEL_INSTALLER=false
          - INSTALL_XLSWRITER=false
          - INSTALL_DEPLOYER=false
          - INSTALL_PRESTISSIMO=false
          - INSTALL_LINUXBREW=false
          - INSTALL_MC=false
          - INSTALL_SYMFONY=false
          - INSTALL_PYTHON=false
          - INSTALL_PYTHON3=false
          - INSTALL_IMAGE_OPTIMIZERS=false
          - INSTALL_IMAGEMAGICK=false
          - INSTALL_TERRAFORM=false
          - INSTALL_DUSK_DEPS=false
          - INSTALL_PG_CLIENT=false
          - INSTALL_PHALCON=false
          - INSTALL_SWOOLE=false
          - INSTALL_TAINT=false
          - INSTALL_LIBPNG=false
          - INSTALL_GRAPHVIZ=false
          - INSTALL_IONCUBE=false
          - INSTALL_MYSQL_CLIENT=false
          - INSTALL_PING=false
          - INSTALL_SSHPASS=false
          - INSTALL_INOTIFY=false
          - INSTALL_FSWATCH=false
          - INSTALL_AST=true
          - INSTALL_YAML=false
          - INSTALL_RDKAFKA=false
          - INSTALL_MAILPARSE=false
          - INSTALL_GIT_PROMPT=false
          - INSTALL_XMLRPC=false
          - PUID=1000
          - PGID=1000
          - CHROME_DRIVER_VERSION=2.42
          - NODE_VERSION=node
          - YARN_VERSION=latest
          - DRUSH_VERSION=8.4.6
          - AST_VERSION=1.0.10
          - IMAGEMAGICK_VERSION=latest
          - TZ=UTC
          - BLACKFIRE_CLIENT_ID=<client_id>
          - BLACKFIRE_CLIENT_TOKEN=<client_token>
          - INSTALL_POWERLINE=false
          - INSTALL_SUPERVISOR=false
          - INSTALL_FFMPEG=false
          - INSTALL_AUDIOWAVEFORM=false
          - INSTALL_WKHTMLTOPDF=false
          - INSTALL_GNU_PARALLEL=false
          - INSTALL_LNAV=false
          - INSTALL_PROTOC=false
          - INSTALL_PHPDECIMAL=false
          - INSTALL_ZOOKEEPER=false
          - INSTALL_SSDB=false
          - INSTALL_TRADER=false
          - PROTOC_VERSION=latest
          - INSTALL_DOCKER_CLIENT=false
          - INSTALL_MEMCACHED=true
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ../:/var/www:cached
        - docker-in-docker:/certs/client
        - ./php-worker/supervisord.d:/etc/supervisord.d
      extra_hosts:
        - "dockerhost:10.0.75.1"
      ports:
        - "2222:22"
        - "3000:3000"
        - "3001:3001"
        - "8080:8080"
        - "8001:8000"
        - "4200:4200"
      tty: true
      environment:
        - PHP_IDE_CONFIG=serverName=laradock
        - DOCKER_HOST=tcp://docker-in-docker:2376
        - DOCKER_TLS_VERIFY=1
        - DOCKER_TLS_CERTDIR=/certs
        - DOCKER_CERT_PATH=/certs/client
        - CHOKIDAR_USEPOLLING=true
      networks:
        - frontend
        - backend
      links:
        - docker-in-docker

### PHP-FPM ##############################################
    php-fpm:
      build:
        context: ./php-fpm
        args:
          - CHANGE_SOURCE=false
          - BASE_IMAGE_TAG_PREFIX=latest
          - LARADOCK_PHP_VERSION=8.0
          - LARADOCK_PHALCON_VERSION=4.0.5
          - INSTALL_BZ2=false
          - INSTALL_ENCHANT=false
          - INSTALL_GMP=false
          - INSTALL_GNUPG=false
          - INSTALL_XDEBUG=false
          - INSTALL_PCOV=false
          - INSTALL_PHPDBG=false
          - INSTALL_BLACKFIRE=false
          - INSTALL_SSH2=false
          - INSTALL_SOAP=false
          - INSTALL_XSL=false
          - INSTALL_SMB=false
          - INSTALL_IMAP=false
          - INSTALL_MONGO=false
          - INSTALL_AMQP=false
          - INSTALL_CASSANDRA=false
          - INSTALL_ZMQ=false
          - INSTALL_GEARMAN=false
          - INSTALL_MSSQL=false
          - INSTALL_BCMATH=true
          - INSTALL_PHPREDIS=true
          - INSTALL_MEMCACHED=false
          - INSTALL_OPCACHE=true
          - INSTALL_EXIF=false
          - INSTALL_AEROSPIKE=false
          - INSTALL_OCI8=false
          - INSTALL_MYSQLI=true
          - INSTALL_PGSQL=false
          - INSTALL_PG_CLIENT=false
          - INSTALL_POSTGIS=false
          - INSTALL_INTL=true
          - INSTALL_GHOSTSCRIPT=false
          - INSTALL_LDAP=false
          - INSTALL_PHALCON=false
          - INSTALL_SWOOLE=false
          - INSTALL_TAINT=false
          - INSTALL_IMAGE_OPTIMIZERS=true
          - INSTALL_IMAGEMAGICK=true
          - INSTALL_CALENDAR=false
          - INSTALL_XLSWRITER=false
          - INSTALL_FAKETIME=false
          - INSTALL_IONCUBE=false
          - INSTALL_APCU=false
          - INSTALL_CACHETOOL=false
          - INSTALL_YAML=false
          - INSTALL_RDKAFKA=false
          - INSTALL_GETTEXT=false
          - INSTALL_ADDITIONAL_LOCALES=false
          - INSTALL_MYSQL_CLIENT=false
          - INSTALL_PING=false
          - INSTALL_SSHPASS=false
          - INSTALL_MAILPARSE=false
          - INSTALL_PCNTL=false
          - ADDITIONAL_LOCALES=en_US.UTF-8 es_ES.UTF-8 fr_FR.UTF-8
          - INSTALL_FFMPEG=false
          - INSTALL_AUDIOWAVEFORM=false
          - INSTALL_WKHTMLTOPDF=false
          - INSTALL_XHPROF=false
          - INSTALL_XMLRPC=false
          - INSTALL_PHPDECIMAL=false
          - INSTALL_ZOOKEEPER=false
          - INSTALL_SSDB=false
          - INSTALL_TRADER=false
          - DOWNGRADE_OPENSSL_TLS_AND_SECLEVEL=false
          - PUID=1000
          - PGID=1000
          - IMAGEMAGICK_VERSION=latest
          - LOCALE=POSIX
          - PHP_FPM_NEW_RELIC=false
          - PHP_FPM_NEW_RELIC_KEY=0000
          - PHP_FPM_NEW_RELIC_APP_NAME=app_name
          - INSTALL_DOCKER_CLIENT=false
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ./php-fpm/php8.0.ini:/usr/local/etc/php/php.ini
        - ../:/var/www:cached
        - docker-in-docker:/certs/client
      ports:
        - "9003:9003"
      expose:
        - "9000"
      extra_hosts:
        - "dockerhost:10.0.75.1"
      environment:
        - PHP_IDE_CONFIG=serverName=laradock
        - DOCKER_HOST=tcp://docker-in-docker:2376
        - DOCKER_TLS_VERIFY=1
        - DOCKER_TLS_CERTDIR=/certs
        - DOCKER_CERT_PATH=/certs/client
        - FAKETIME=-0
      depends_on:
        - workspace
      networks:
        - backend

### PHP Worker ############################################
    php-worker:
      build:
        context: ./php-worker
        args:
          - CHANGE_SOURCE=false
          - LARADOCK_PHP_VERSION=8.0
          - PHALCON_VERSION=4.0.5
          - INSTALL_BZ2=false
          - INSTALL_GD=false
          - INSTALL_IMAGEMAGICK=false
          - INSTALL_GMP=false
          - INSTALL_GNUPG=false
          - INSTALL_LDAP=false
          - INSTALL_PGSQL=false
          - INSTALL_MONGO=false
          - INSTALL_BCMATH=false
          - INSTALL_MEMCACHED=false
          - INSTALL_OCI8=false
          - INSTALL_MSSQL=false
          - INSTALL_PHALCON=false
          - INSTALL_XLSWRITER=false
          - INSTALL_SOAP=false
          - INSTALL_ZIP_ARCHIVE=false
          - INSTALL_MYSQL_CLIENT=false
          - INSTALL_AMQP=false
          - INSTALL_CASSANDRA=false
          - INSTALL_GEARMAN=false
          - INSTALL_GHOSTSCRIPT=false
          - INSTALL_SWOOLE=false
          - INSTALL_TAINT=false
          - INSTALL_FFMPEG=false
          - INSTALL_AUDIOWAVEFORM=false
          - INSTALL_REDIS=false
          - INSTALL_IMAP=false
          - INSTALL_XMLRPC=false
          - INSTALL_SSDB=false
          - PUID=1000
          - PGID=1000
          - IMAGEMAGICK_VERSION=latest
      volumes:
        - ../:/var/www:cached
        - ./php-worker/supervisord.d:/etc/supervisord.d
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:10.0.75.1"
      networks:
        - backend
### Laravel Horizon ############################################
    laravel-horizon:
      build:
        context: ./laravel-horizon
        args:
          - CHANGE_SOURCE=false
          - LARADOCK_PHP_VERSION=8.0
          - INSTALL_BZ2=false
          - INSTALL_GD=false
          - INSTALL_GMP=false
          - INSTALL_GNUPG=false
          - INSTALL_LDAP=false
          - INSTALL_IMAGEMAGICK=false
          - INSTALL_PGSQL=false
          - INSTALL_ZIP_ARCHIVE=false
          - INSTALL_BCMATH=true
          - INSTALL_MEMCACHED=false
          - INSTALL_SOCKETS=false
          - INSTALL_YAML=false
          - INSTALL_CASSANDRA=false
          - INSTALL_PHPREDIS=false
          - INSTALL_MONGO=false
          - INSTALL_FFMPEG=false
          - INSTALL_AUDIOWAVEFORM=false
          - PUID=1000
          - PGID=1000
          - IMAGEMAGICK_VERSION=latest
      volumes:
        - ../:/var/www
        - ./laravel-horizon/supervisord.d:/etc/supervisord.d
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:10.0.75.1"
      networks:
        - backend

### Apache Server ########################################
    apache2:
      build:
        context: ./apache2
        args:
          - PHP_UPSTREAM_CONTAINER=php-fpm
          - PHP_UPSTREAM_PORT=9000
          - PHP_UPSTREAM_TIMEOUT=60
          - DOCUMENT_ROOT=/var/www/
          - APACHE_INSTALL_HTTP2=false
      volumes:
        - ../:/var/www:cached
        - ./logs/apache2:/var/log/apache2
        - ./apache2/sites:/etc/apache2/sites-available
        - ./apache2/ssl/:/etc/apache2/ssl
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend

### MySQL ################################################
    mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=latest
      environment:
        - MYSQL_DATABASE=default
        - MYSQL_USER=default
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=root
        - TZ=UTC
      volumes:
        - /home/mxadmin/.laradock/data/mysql:/var/lib/mysql
        - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "3306:3306"
      networks:
        - backend

### MSSQL ################################################
    mssql:
      build:
        context: ./mssql
      environment:
        - MSSQL_PID=Express
        - MSSQL_DATABASE=master
        - SA_PASSWORD=yourStrong(!)Password
        - ACCEPT_EULA=Y
      volumes:
        - mssql:/var/opt/mssql
      ports:
        - "1433:1433"
      networks:
        - backend

### MariaDB ##############################################
    mariadb:
      build:
        context: ./mariadb
        args:
          - http_proxy
          - https_proxy
          - no_proxy
          - MARIADB_VERSION=latest
      volumes:
        - /home/mxadmin/.laradock/data/mariadb:/var/lib/mysql
        - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "3308:3308"
      environment:
        - TZ=UTC
        - MYSQL_DATABASE=default
        - MYSQL_USER=default
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=root
      networks:
        - backend


  ### Redis ################################################
    redis:
      build: ./redis
      volumes:
        - ~/.laradock/data/redis:/data
      command: --requirepass secret_redis
      ports:
        - "6379:6379"
      networks:
        - backend

### Redis Cluster ##########################################
    redis-cluster:
      build: ./redis-cluster
      ports:
        - "7000-7005:7000-7005"
      networks:
        - backend



### Memcached ############################################
    memcached:
      build: ./memcached
      volumes:
        - /home/mxadmin/.laradock/data/memcached:/var/lib/memcached
      ports:
        - "11211:11211"
      depends_on:
        - php-fpm
      networks:
        - backend



### phpMyAdmin ###########################################
    phpmyadmin:
      build: ./phpmyadmin
      environment:
        - PMA_ARBITRARY=1
        - MYSQL_USER=default
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=secret
        - MAX_EXECUTION_TIME=600
        - MEMORY_LIMIT=256M
        - UPLOAD_LIMIT=2G
      ports:
        - "8081:80"
      depends_on:
        - "mysql"
      networks:
        - frontend
        - backend

### Adminer ###########################################
    adminer:
      build:
        context: ./adminer
        args:
          - INSTALL_MSSQL=false
      environment:
          - ADMINER_PLUGINS=
          - ADMINER_DESIGN=pepa-linha
          - ADMINER_DEFAULT_SERVER=mysql
      ports:
        - "8088:8080"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend


### Certbot #########################################
    certbot:
      build:
        context: ./certbot
      volumes:
        - ./data/certbot/certs/:/var/certs
        - ./certbot/letsencrypt/:/var/www/letsencrypt
      environment:
        - CN="fake.domain.com"
        - EMAIL="fake.email@gmail.com"
      networks:
        - frontend


### Mailhog ################################################
    mailhog:
      build: ./mailhog
      ports:
        - "1025:1025"
        - "8025:8025"
      networks:
        - frontend
        - backend



### Laravel Echo Server #######################################
    laravel-echo-server:
      build:
        context: ./laravel-echo-server
        args:
          - CHANGE_SOURCE=false
      volumes:
        - ./laravel-echo-server/laravel-echo-server.json:/app/laravel-echo-server.json:ro
      ports:
        - "6001:6001"
      links:
        - redis
      networks:
        - frontend
        - backend


### Docker-in-Docker ################################################
    docker-in-docker:
      image: docker:20.10-dind
      environment:
        DOCKER_TLS_SAN: DNS:docker-in-docker
      privileged: true
      volumes:
        - ../:/var/www
        - docker-in-docker:/certs/client
      expose:
        - 2375
      networks:
        - backend

### REDISWEBUI ################################################
    redis-webui:
      build:
        context: ./redis-webui
      environment:
        - ADMIN_USER=laradock
        - ADMIN_PASS=laradock
        - REDIS_1_HOST=redis
        - REDIS_1_PORT=6379
      networks:
        - backend
      ports:
        - "9987:80"
      depends_on:
        - redis




### SWAGGER EDITOR ############################################
    swagger-editor:
      build: ./swagger-editor
      ports:
        - 5151:8080
      networks:
        - backend

### SWAGGER UI ################################################
    swagger-ui:
      build: ./swagger-ui
      environment:
        - API_URL=http://generator.swagger.io/api/swagger.json
      ports:
        - 5555:8080
      networks:
        - backend


